image: docker:git
services:
  - docker:dind

stages:
- build

variables:
  REGISTRY_ENDPOINT: registry-special.tenforce.com
  REGISTRY_IMAGE: registry-special.tenforce.com/special/demonstrator-log-generator
  RELEASE_IMAGE: ${REGISTRY_IMAGE}:latest
  TAG_IMAGE: ${REGISTRY_IMAGE}:${CI_COMMIT_TAG}

before_script:
  - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_ENDPOINT}

build:
  stage: build
  script: docker build .
  except:
    - master
    - tags

build-and-push:
  stage: build
  script:
    - target=$([ "${CI_COMMIT_REF_NAME}" = "master" ] && echo latest || echo "${CI_COMMIT_REF_NAME}")
    - docker build -t ${REGISTRY_IMAGE}:${target} .
    - docker push "${REGISTRY_IMAGE}:${target}"
  only:
    - master
    - tags
